alphavantage:
  client:
    url: "https://www.alphavantage.co/query"
    fn: "DIGITAL_CURRENCY_DAILY"
    apiKey: "KIKJ1AN4SPAXV1BO"
app:
  limit:
    data:
      currency: 365
  release:
    env: "prod"
  server:
    port: 8090
    readTimeout: 10
    writeTimeout: 10
  currencies:
    allowed:
      - "BTC"
      - "MATIC"
      - "ADA"
      - "ETH"
    exchange:
      - "INR"
