basePath: /
definitions:
  alphavantage.DailyCurrencyDataResponse:
    properties:
      Meta Data:
        $ref: '#/definitions/alphavantage.MetaData'
      Time Series (Digital Currency Daily):
        additionalProperties:
          $ref: '#/definitions/alphavantage.PriceDataResponse'
        type: object
    type: object
  alphavantage.MetaData:
    properties:
      2. Digital Currency Code:
        type: string
      3. Digital Currency Name:
        type: string
      4. Market Code:
        type: string
      5. Market Name:
        type: string
      6. Last Refreshed:
        type: string
      7. Time Zone:
        type: string
    type: object
  alphavantage.PriceDataResponse:
    properties:
      2a. high (INR):
        type: string
      2b. high (USD):
        type: string
    type: object
  app.CurrenciesResponse:
    properties:
      code:
        type: integer
      data:
        items:
          type: string
        type: array
      msg:
        type: string
    type: object
  app.CurrencyDataResponse:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/alphavantage.DailyCurrencyDataResponse'
      msg:
        type: string
    type: object
  app.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
info:
  contact:
    email: singh_kshitij@yahoo.com
    name: Kshitij
    url: https://github.com/singhkshitij
  description: This is a sample server Canny server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Canny documentation
  version: "1.0"
paths:
  /api/v1/currencies:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.CurrenciesResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Get supported currencies
      tags:
      - currency
  /api/v1/currencies/{currency}:
    get:
      parameters:
      - description: Symbol
        in: path
        name: currency
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.CurrencyDataResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Get coin data
      tags:
      - currency
  /ping:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: health check endpoint
      tags:
      - health-check
swagger: "2.0"
